# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/fquispe/Escritorio/uba-aed3-tp3-2c-2019

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/fquispe/Escritorio/uba-aed3-tp3-2c-2019

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/fquispe/Escritorio/uba-aed3-tp3-2c-2019/CMakeFiles /home/fquispe/Escritorio/uba-aed3-tp3-2c-2019/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/fquispe/Escritorio/uba-aed3-tp3-2c-2019/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named test-32

# Build rule for target.
test-32: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test-32
.PHONY : test-32

# fast build rule for target.
test-32/fast:
	$(MAKE) -f CMakeFiles/test-32.dir/build.make CMakeFiles/test-32.dir/build
.PHONY : test-32/fast

#=============================================================================
# Target rules for targets named savings-main

# Build rule for target.
savings-main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 savings-main
.PHONY : savings-main

# fast build rule for target.
savings-main/fast:
	$(MAKE) -f CMakeFiles/savings-main.dir/build.make CMakeFiles/savings-main.dir/build
.PHONY : savings-main/fast

src/algorithms/SavingsEuristic.o: src/algorithms/SavingsEuristic.cpp.o

.PHONY : src/algorithms/SavingsEuristic.o

# target to build an object file
src/algorithms/SavingsEuristic.cpp.o:
	$(MAKE) -f CMakeFiles/savings-main.dir/build.make CMakeFiles/savings-main.dir/src/algorithms/SavingsEuristic.cpp.o
.PHONY : src/algorithms/SavingsEuristic.cpp.o

src/algorithms/SavingsEuristic.i: src/algorithms/SavingsEuristic.cpp.i

.PHONY : src/algorithms/SavingsEuristic.i

# target to preprocess a source file
src/algorithms/SavingsEuristic.cpp.i:
	$(MAKE) -f CMakeFiles/savings-main.dir/build.make CMakeFiles/savings-main.dir/src/algorithms/SavingsEuristic.cpp.i
.PHONY : src/algorithms/SavingsEuristic.cpp.i

src/algorithms/SavingsEuristic.s: src/algorithms/SavingsEuristic.cpp.s

.PHONY : src/algorithms/SavingsEuristic.s

# target to generate assembly for a file
src/algorithms/SavingsEuristic.cpp.s:
	$(MAKE) -f CMakeFiles/savings-main.dir/build.make CMakeFiles/savings-main.dir/src/algorithms/SavingsEuristic.cpp.s
.PHONY : src/algorithms/SavingsEuristic.cpp.s

src/entities/core/Dot.o: src/entities/core/Dot.cpp.o

.PHONY : src/entities/core/Dot.o

# target to build an object file
src/entities/core/Dot.cpp.o:
	$(MAKE) -f CMakeFiles/savings-main.dir/build.make CMakeFiles/savings-main.dir/src/entities/core/Dot.cpp.o
.PHONY : src/entities/core/Dot.cpp.o

src/entities/core/Dot.i: src/entities/core/Dot.cpp.i

.PHONY : src/entities/core/Dot.i

# target to preprocess a source file
src/entities/core/Dot.cpp.i:
	$(MAKE) -f CMakeFiles/savings-main.dir/build.make CMakeFiles/savings-main.dir/src/entities/core/Dot.cpp.i
.PHONY : src/entities/core/Dot.cpp.i

src/entities/core/Dot.s: src/entities/core/Dot.cpp.s

.PHONY : src/entities/core/Dot.s

# target to generate assembly for a file
src/entities/core/Dot.cpp.s:
	$(MAKE) -f CMakeFiles/savings-main.dir/build.make CMakeFiles/savings-main.dir/src/entities/core/Dot.cpp.s
.PHONY : src/entities/core/Dot.cpp.s

src/entities/entrypoint/InputCVRP.o: src/entities/entrypoint/InputCVRP.cpp.o

.PHONY : src/entities/entrypoint/InputCVRP.o

# target to build an object file
src/entities/entrypoint/InputCVRP.cpp.o:
	$(MAKE) -f CMakeFiles/savings-main.dir/build.make CMakeFiles/savings-main.dir/src/entities/entrypoint/InputCVRP.cpp.o
.PHONY : src/entities/entrypoint/InputCVRP.cpp.o

src/entities/entrypoint/InputCVRP.i: src/entities/entrypoint/InputCVRP.cpp.i

.PHONY : src/entities/entrypoint/InputCVRP.i

# target to preprocess a source file
src/entities/entrypoint/InputCVRP.cpp.i:
	$(MAKE) -f CMakeFiles/savings-main.dir/build.make CMakeFiles/savings-main.dir/src/entities/entrypoint/InputCVRP.cpp.i
.PHONY : src/entities/entrypoint/InputCVRP.cpp.i

src/entities/entrypoint/InputCVRP.s: src/entities/entrypoint/InputCVRP.cpp.s

.PHONY : src/entities/entrypoint/InputCVRP.s

# target to generate assembly for a file
src/entities/entrypoint/InputCVRP.cpp.s:
	$(MAKE) -f CMakeFiles/savings-main.dir/build.make CMakeFiles/savings-main.dir/src/entities/entrypoint/InputCVRP.cpp.s
.PHONY : src/entities/entrypoint/InputCVRP.cpp.s

src/entities/entrypoint/OutputCVRP.o: src/entities/entrypoint/OutputCVRP.cpp.o

.PHONY : src/entities/entrypoint/OutputCVRP.o

# target to build an object file
src/entities/entrypoint/OutputCVRP.cpp.o:
	$(MAKE) -f CMakeFiles/savings-main.dir/build.make CMakeFiles/savings-main.dir/src/entities/entrypoint/OutputCVRP.cpp.o
.PHONY : src/entities/entrypoint/OutputCVRP.cpp.o

src/entities/entrypoint/OutputCVRP.i: src/entities/entrypoint/OutputCVRP.cpp.i

.PHONY : src/entities/entrypoint/OutputCVRP.i

# target to preprocess a source file
src/entities/entrypoint/OutputCVRP.cpp.i:
	$(MAKE) -f CMakeFiles/savings-main.dir/build.make CMakeFiles/savings-main.dir/src/entities/entrypoint/OutputCVRP.cpp.i
.PHONY : src/entities/entrypoint/OutputCVRP.cpp.i

src/entities/entrypoint/OutputCVRP.s: src/entities/entrypoint/OutputCVRP.cpp.s

.PHONY : src/entities/entrypoint/OutputCVRP.s

# target to generate assembly for a file
src/entities/entrypoint/OutputCVRP.cpp.s:
	$(MAKE) -f CMakeFiles/savings-main.dir/build.make CMakeFiles/savings-main.dir/src/entities/entrypoint/OutputCVRP.cpp.s
.PHONY : src/entities/entrypoint/OutputCVRP.cpp.s

src/executables/output_example.o: src/executables/output_example.cpp.o

.PHONY : src/executables/output_example.o

# target to build an object file
src/executables/output_example.cpp.o:
	$(MAKE) -f CMakeFiles/test-32.dir/build.make CMakeFiles/test-32.dir/src/executables/output_example.cpp.o
.PHONY : src/executables/output_example.cpp.o

src/executables/output_example.i: src/executables/output_example.cpp.i

.PHONY : src/executables/output_example.i

# target to preprocess a source file
src/executables/output_example.cpp.i:
	$(MAKE) -f CMakeFiles/test-32.dir/build.make CMakeFiles/test-32.dir/src/executables/output_example.cpp.i
.PHONY : src/executables/output_example.cpp.i

src/executables/output_example.s: src/executables/output_example.cpp.s

.PHONY : src/executables/output_example.s

# target to generate assembly for a file
src/executables/output_example.cpp.s:
	$(MAKE) -f CMakeFiles/test-32.dir/build.make CMakeFiles/test-32.dir/src/executables/output_example.cpp.s
.PHONY : src/executables/output_example.cpp.s

src/executables/savings-main.o: src/executables/savings-main.cpp.o

.PHONY : src/executables/savings-main.o

# target to build an object file
src/executables/savings-main.cpp.o:
	$(MAKE) -f CMakeFiles/savings-main.dir/build.make CMakeFiles/savings-main.dir/src/executables/savings-main.cpp.o
.PHONY : src/executables/savings-main.cpp.o

src/executables/savings-main.i: src/executables/savings-main.cpp.i

.PHONY : src/executables/savings-main.i

# target to preprocess a source file
src/executables/savings-main.cpp.i:
	$(MAKE) -f CMakeFiles/savings-main.dir/build.make CMakeFiles/savings-main.dir/src/executables/savings-main.cpp.i
.PHONY : src/executables/savings-main.cpp.i

src/executables/savings-main.s: src/executables/savings-main.cpp.s

.PHONY : src/executables/savings-main.s

# target to generate assembly for a file
src/executables/savings-main.cpp.s:
	$(MAKE) -f CMakeFiles/savings-main.dir/build.make CMakeFiles/savings-main.dir/src/executables/savings-main.cpp.s
.PHONY : src/executables/savings-main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... test-32"
	@echo "... savings-main"
	@echo "... src/algorithms/SavingsEuristic.o"
	@echo "... src/algorithms/SavingsEuristic.i"
	@echo "... src/algorithms/SavingsEuristic.s"
	@echo "... src/entities/core/Dot.o"
	@echo "... src/entities/core/Dot.i"
	@echo "... src/entities/core/Dot.s"
	@echo "... src/entities/entrypoint/InputCVRP.o"
	@echo "... src/entities/entrypoint/InputCVRP.i"
	@echo "... src/entities/entrypoint/InputCVRP.s"
	@echo "... src/entities/entrypoint/OutputCVRP.o"
	@echo "... src/entities/entrypoint/OutputCVRP.i"
	@echo "... src/entities/entrypoint/OutputCVRP.s"
	@echo "... src/executables/output_example.o"
	@echo "... src/executables/output_example.i"
	@echo "... src/executables/output_example.s"
	@echo "... src/executables/savings-main.o"
	@echo "... src/executables/savings-main.i"
	@echo "... src/executables/savings-main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

